name: test-tickets

on:
  pull_request:
    paths:
      - path: 'tickets/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd tickets
          npm install
          npm run test:ci
