name: test-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          cd auth
          npm install
          npm run test:ci
