name: tests-orders

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: |
          cd orders
          npm install
          npm run test:ci
